---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '7'
    k8s.kuboard.cn/displayName: nginx-all
    k8s.kuboard.cn/ingress: 'true'
    k8s.kuboard.cn/service: ClusterIP
    k8s.kuboard.cn/workload: nginx-all
  generation: 7
  labels:
    k8s.kuboard.cn/layer: web
    k8s.kuboard.cn/name: nginx-all
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      manager: Mozilla
      operation: Update
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      manager: kube-controller-manager
      operation: Update
  name: nginx-all
  namespace: young-sit
  selfLink: /apis/apps/v1/namespaces/young-sit/deployments/nginx-all
  uid: 71e22c77-de73-47db-a688-ba3e92886b41
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: web
      k8s.kuboard.cn/name: nginx-all
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/layer: web
        k8s.kuboard.cn/name: nginx-all
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          lifecycle: {}
          name: nginx-all
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-conf
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aliyun
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seLinuxOptions: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /data/yqkj/nginx/default.conf
            type: File
          name: nginx-conf